src/Entity/Competence.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CompetenceRepository")
 */
class Competence
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name_competence;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $img_comp;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $texte_competence;

    public function getId()
    {
        return $this->id;
    }

    public function getNameCompetence(): ?string
    {
        return $this->name_competence;
    }

    public function setNameCompetence(?string $name_competence): self
    {
        $this->name_competence = $name_competence;

        return $this;
    }

    public function getImgComp(): ?string
    {
        return $this->img_comp;
    }

    public function setImgComp(?string $img_comp): self
    {
        $this->img_comp = $img_comp;

        return $this;
    }

    public function getTexteCompetence(): ?string
    {
        return $this->texte_competence;
    }

    public function setTexteCompetence(?string $texte_competence): self
    {
        $this->texte_competence = $texte_competence;

        return $this;
    }
}

src/Form/CompetenceType.php
<?php

namespace App\Form;

use App\Entity\Competence;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CompetenceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name_competence')
            ->add('img_comp')
            ->add('texte_competence')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Competence::class,
        ]);
    }
}

src/Controller/CompetenceController.php
<?php

namespace App\Controller;

use App\Entity\Competence;
use App\Form\CompetenceType;
use App\Repository\CompetenceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("admin/competence")
 */
class CompetenceController extends Controller
{
    /**
     * @Route("/", name="competence_index", methods="GET")
     */
    public function index(CompetenceRepository $competenceRepository): Response
    {
        return $this->render('competence/index.html.twig', ['competences' => $competenceRepository->findAll()]);
    }

    /**
     * @Route("/new", name="competence_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $competence = new Competence();
        $form = $this->createForm(CompetenceType::class, $competence);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($competence);
            $em->flush();

            return $this->redirectToRoute('competence_index');
        }

        return $this->render('competence/new.html.twig', [
            'competence' => $competence,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="competence_show", methods="GET")
     */
    public function show(Competence $competence): Response
    {
        return $this->render('competence/show.html.twig', ['competence' => $competence]);
    }

    /**
     * @Route("/{id}/edit", name="competence_edit", methods="GET|POST")
     */
    public function edit(Request $request, Competence $competence): Response
    {
        $form = $this->createForm(CompetenceType::class, $competence);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('competence_edit', ['id' => $competence->getId()]);
        }

        return $this->render('competence/edit.html.twig', [
            'competence' => $competence,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="competence_delete", methods="DELETE")
     */
    public function delete(Request $request, Competence $competence): Response
    {
        if ($this->isCsrfTokenValid('delete'.$competence->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($competence);
            $em->flush();
        }

        return $this->redirectToRoute('competence_index');
    }
}

templates/competence/_delete_form.html.twig
<form method="post" action="{{ path('competence_delete', {'id': competence.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ competence.id) }}">
    <button class="btn">Delete</button>
</form>

templates/competence/_form.html.twig
<div class='form-group'>
    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}
</div>

templates/competence/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Competence{% endblock %}

{% block body %}
    <h1>Edit Competence</h1>

    {{ include('competence/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('competence_index') }}">back to list</a>

    {{ include('competence/_delete_form.html.twig') }}
{% endblock %}

templates/competence/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Competence index{% endblock %}

{% block header %}
    {{ knp_menu_render('main') }}
{% endblock %}

{% block main %}
    <h1>Competence index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name_competence</th>
                <th>Img_comp</th>
                <th>Texte_competence</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for competence in competences %}
            <tr>
                <td>{{ competence.id }}</td>
                <td>{{ competence.nameCompetence }}</td>
                <td>{{ competence.imgComp }}</td>
                <td>{{ competence.texteCompetence }}</td>
                <td>
                    <a href="{{ path('competence_show', {'id': competence.id}) }}" class="badge badge-primary">show</a>
                    <a href="{{ path('competence_edit', {'id': competence.id}) }}" class="badge badge-primary">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class='row'>
        <div class='col-10'></div>
        <a href="{{ path('competence_new') }}" class='btn btn-primary'>new</a>
    </div>
{% endblock %}

templates/competence/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Competence{% endblock %}

{% block body %}
    <h1>Create new Competence</h1>

    {{ include('competence/_form.html.twig') }}

    <a href="{{ path('competence_index') }}">back to list</a>
{% endblock %}

templates/competence/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Competence{% endblock %}

{% block body %}
    <h1>Competence</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ competence.id }}</td>
            </tr>
            <tr>
                <th>Name_competence</th>
                <td>{{ competence.nameCompetence }}</td>
            </tr>
            <tr>
                <th>Img_comp</th>
                <td>{{ competence.imgComp }}</td>
            </tr>
            <tr>
                <th>Texte_competence</th>
                <td>{{ competence.texteCompetence }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('competence_index') }}">back to list</a>

    <a href="{{ path('competence_edit', {'id': competence.id}) }}">edit</a>

    {{ include('competence/_delete_form.html.twig') }}
{% endblock %}