src/Entity/Project.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProjectRepository")
 */
class Project
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name_project;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_project;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description_project;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image_project;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $github_project;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $link_project;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Category", inversedBy="projects")
     */
    private $category;

    public function __construct()
    {
        $this->category = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getNameProject(): ?string
    {
        return $this->name_project;
    }

    public function setNameProject(?string $name_project): self
    {
        $this->name_project = $name_project;

        return $this;
    }

    public function getDateProject(): ?\DateTimeInterface
    {
        return $this->date_project;
    }

    public function setDateProject(?\DateTimeInterface $date_project): self
    {
        $this->date_project = $date_project;

        return $this;
    }

    public function getDescriptionProject(): ?string
    {
        return $this->description_project;
    }

    public function setDescriptionProject(?string $description_project): self
    {
        $this->description_project = $description_project;

        return $this;
    }

    public function getImageProject(): ?string
    {
        return $this->image_project;
    }

    public function setImageProject(?string $image_project): self
    {
        $this->image_project = $image_project;

        return $this;
    }

    public function getGithubProject(): ?string
    {
        return $this->github_project;
    }

    public function setGithubProject(?string $github_project): self
    {
        $this->github_project = $github_project;

        return $this;
    }

    public function getLinkProject(): ?string
    {
        return $this->link_project;
    }

    public function setLinkProject(?string $link_project): self
    {
        $this->link_project = $link_project;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategory(): Collection
    {
        return $this->category;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->category->contains($category)) {
            $this->category[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->category->contains($category)) {
            $this->category->removeElement($category);
        }

        return $this;
    }
    public function __toString(){
        return (string) $this->name_project;
    }
}

src/Form/ProjectType.php
<?php

namespace App\Form;

use App\Entity\Project;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProjectType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name_project')
            ->add('date_project')
            ->add('description_project')
            ->add('image_project')
            ->add('github_project')
            ->add('link_project')
            ->add('category')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Project::class,
        ]);
    }
}

src/Controller/ProjectController.php
<?php

namespace App\Controller;

use App\Entity\Project;
use App\Form\ProjectType;
use App\Repository\ProjectRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("admin/project")
 */
class ProjectController extends Controller
{
    /**
     * @Route("/", name="project_index", methods="GET")
     */
    public function index(ProjectRepository $projectRepository): Response
    {
        return $this->render('project/index.html.twig', ['projects' => $projectRepository->findAll()]);
    }

    /**
     * @Route("/new", name="project_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $project = new Project();
        $form = $this->createForm(ProjectType::class, $project);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($project);
            $em->flush();

            return $this->redirectToRoute('project_index');
        }

        return $this->render('project/new.html.twig', [
            'project' => $project,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="project_show", methods="GET")
     */
    public function show(Project $project): Response
    {
        return $this->render('project/show.html.twig', ['project' => $project]);
    }

    /**
     * @Route("/{id}/edit", name="project_edit", methods="GET|POST")
     */
    public function edit(Request $request, Project $project): Response
    {
        $form = $this->createForm(ProjectType::class, $project);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('project_edit', ['id' => $project->getId()]);
        }

        return $this->render('project/edit.html.twig', [
            'project' => $project,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="project_delete", methods="DELETE")
     */
    public function delete(Request $request, Project $project): Response
    {
        if ($this->isCsrfTokenValid('delete'.$project->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($project);
            $em->flush();
        }

        return $this->redirectToRoute('project_index');
    }
}

templates/project/_delete_form.html.twig
<form method="post" action="{{ path('project_delete', {'id': project.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ project.id) }}">
    <button class="btn">Delete</button>
</form>

templates/project/_form.html.twig
<div class='form-group'>
    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}
</div>

templates/project/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Project{% endblock %}

{% block body %}
    <h1>Edit Project</h1>

    {{ include('project/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('project_index') }}">back to list</a>

    {{ include('project/_delete_form.html.twig') }}
{% endblock %}

templates/project/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Project index{% endblock %}

{% block header %}
    {{ knp_menu_render('main') }}
{% endblock %}

{% block main %}
    <h1>Project index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name_project</th>
                <th>Date_project</th>
                <th>Description_project</th>
                <th>Image_project</th>
                <th>Github_project</th>
                <th>Link_project</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for project in projects %}
            <tr>
                <td>{{ project.id }}</td>
                <td>{{ project.nameProject }}</td>
                <td>{{ project.dateProject ? project.dateProject|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ project.descriptionProject }}</td>
                <td>{{ project.imageProject }}</td>
                <td>{{ project.githubProject }}</td>
                <td>{{ project.linkProject }}</td>
                <td>
                    <a href="{{ path('project_show', {'id': project.id}) }}" class="badge badge-primary">show</a>
                    <a href="{{ path('project_edit', {'id': project.id}) }}" class="badge badge-primary">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class='row'>
        <div class='col-10'></div>
        <a href="{{ path('project_new') }}" class='btn btn-primary'>new</a>
    </div>
{% endblock %}

templates/project/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Project{% endblock %}

{% block body %}
    <h1>Create new Project</h1>

    {{ include('project/_form.html.twig') }}

    <a href="{{ path('project_index') }}">back to list</a>
{% endblock %}

templates/project/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Project{% endblock %}

{% block body %}
    <h1>Project</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ project.id }}</td>
            </tr>
            <tr>
                <th>Name_project</th>
                <td>{{ project.nameProject }}</td>
            </tr>
            <tr>
                <th>Date_project</th>
                <td>{{ project.dateProject ? project.dateProject|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Description_project</th>
                <td>{{ project.descriptionProject }}</td>
            </tr>
            <tr>
                <th>Image_project</th>
                <td>{{ project.imageProject }}</td>
            </tr>
            <tr>
                <th>Github_project</th>
                <td>{{ project.githubProject }}</td>
            </tr>
            <tr>
                <th>Link_project</th>
                <td>{{ project.linkProject }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('project_index') }}">back to list</a>

    <a href="{{ path('project_edit', {'id': project.id}) }}">edit</a>

    {{ include('project/_delete_form.html.twig') }}
{% endblock %}